# -*- coding: utf-8 -*-
"""uno.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OE3yiwBb62gHmHDgYqDtkPrLA9kCEYhk
"""

class card():
  def __init__(self,suit,value):
    self.suit=suit
    self.value=value

    def show(self):
      print("{} of {}".format(self.value,self.suit))

class deck:
  def __init__(self):
    self.card=[]
    self.build=()

  def build(self):
    for c in ["skip","reverse","draw2","wild","wild draw"]
    for a in range["yellow","green","red","blue"]:
      self.card.append(card(c,a))


    def show(self):
      for c in self.card:
        c.show()


deck=deck()
deck.show()